spring:
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: ZmcyxkFnjSbcWblMdyGIzieOQbMKYMAf
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: ${PORT:8080}
google:
  calendar:
    service-account-email: ${GOOGLE_SERVICE_ACCOUNT_EMAIL:not-configured}
    service-account-key-path: ${GOOGLE_SERVICE_ACCOUNT_KEY_PATH:not-configured}
