spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
server:
  port: ${PORT:8081}
google:
  calendar:
    service-account-email: ${GOOGLE_SERVICE_ACCOUNT_EMAIL:not-configured}
    service-account-key-path: ${GOOGLE_SERVICE_ACCOUNT_KEY_PATH:not-configured}
